Update docker-image.yml

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -16,7 +16,7 @@ jobs:
       contents: read
       security-events: write
     strategy:
-      fail-fast: true  # Arrête le job dès qu'une erreur est rencontrée
+      #fail-fast: true  # Arrête le job dès qu'une erreur est rencontrée
       matrix:
         # Remplacez par les langages présents dans votre projet
         language: [ 'python' ]  # Par exemple, spécifiez uniquement 'python'
@@ -34,8 +34,21 @@ jobs:
         uses: github/codeql-action/analyze@v3  # Passez à v3
         with:
           category: security  # Catégorie d'analyse orientée sécurité
-        continue-on-error: false  # Stoppe l'exécution du job si une vulnérabilité critique est détectée
+       # continue-on-error: false Stoppe l'exécution du job si une vulnérabilité critique est détectée
 
+       # Étape supplémentaire pour vérifier les alertes CodeQL
+      - name: Check for CodeQL alerts
+        id: codeql-alerts
+        run: |
+          echo "Vérification des alertes CodeQL..."
+          ALERTS=$(gh api --paginate repos/${{ github.repository }}/code-scanning/alerts --jq '.[].rule.severity' | grep -E 'high|critical' | wc -l)
+          if [ "$ALERTS" -gt 0 ]; then
+            echo "::error:: Des alertes CodeQL de sévérité élevée ou critique ont été détectées. Nombre d'alertes: $ALERTS"
+            exit 1  # Provoque l'échec du job si des alertes sont détectées
+          else
+            echo "Aucune alerte critique ou élevée détectée par CodeQL."
+          fi
+          
   # Job de build et scan Docker, qui s'exécute seulement si le job codeql-analysis réussit
   build-and-scan:
     needs: codeql-analysis  # Dépend du job codeql-analysis
